// Generated by https://quicktype.io

export interface Credito {
  id:          string;
  nombre:      string;
  tipoCredito: string;
  montoMin:   number;
  montoMax:   number;
  plazoMin:   number;
  plazoMax:   number;
  interesMen: number;
  interesAnualFija: number,
  interesAnualMora: number,
  catPromedio:      number,
  img:        string
}
