// Generated by https://quicktype.io

export interface Credito {
  id:          string;
  nombre:      string;
  tipoCredito: string;
  descripcion?: string;
  caracteristicas?: string;
  venyben?:  string;
  requisitos?: string;
  consideraciones?: string;
  recomendaciones?: string;
  riesgos?:    string;
  montoMin:   number;
  montoMax:   number;
  plazoMin:   number;
  plazoMax:   number;
  interesMen: number;
  interesAnualFija: number;
  interesAnualMora: number;
  catPromedio:      number;
}
