// Generated by https://quicktype.io

export interface Credito {
  id:         string;
  nombre:     string;
  tipoCredito: string;
  montoMin:   number;
  montoMax:   number | string;
  plazoMin:   number;
  plazoMax:   number;
  interesMen: number;
}
